AWSTemplateFormatVersion: '2010-09-09' #Version funcional. 
Description: Cripto-Scraper-Binance-Central-Bank 

Parameters:
  ProjectName:
    Type: String
    Default: Finance-information
  Stage:
    Type: String
    AllowedValues: [dev, prod, qa]
    Default: dev

Mappings:
  LifecycleRules:
    Defaults:
      ExpireDays: 365 #Quiza es mas valido por 90_Dias/ Dudo si. Nos sirve la data historica.

Resources:
  RawBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Stage}-raw'
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOld
            Status: Enabled
            ExpirationInDays: !FindInMap [LifecycleRules, Defaults, ExpireDays]
      Tags:
        - Key: SERVICE
          Value: data-lake
        - Key: STAGE
          Value: !Ref Stage
        - Key: MANAGER
          Value: "mdavila"
        - Key: BIILING_CLIENT
          Value: "contabilidad/finanzas"
#CLEANBUCKET RESOURCE - RAW 
  CleanBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${ProjectName}-${Stage}-clean'
      VersioningConfiguration: { Status: Enabled }
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: SERVICE
          Value: data-lake
        - Key: STAGE
          Value: !Ref Stage
        - Key: MANAGER
          Value: "mdavila"
        - Key: BIILING_CLIENT
          Value: "contabilidad/finanzas"

  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${ProjectName}_${Stage}_db'
        Description: Glue Catalog for curated/clean tables

Outputs:
  RawBucketName:
    Value: !Ref RawBucket
    Export:
      Name: !Sub '${ProjectName}-${Stage}-raw-name'
  CleanBucketName:
    Value: !Ref CleanBucket
    Export:
      Name: !Sub '${ProjectName}-${Stage}-clean-name'
  GlueDatabaseName:
    Value: !GetAtt GlueDatabase.DatabaseInput.Name
    Export:
      Name: !Sub '${ProjectName}-${Stage}-glue-db'
